version: '3.4'
x-common-variables: &common-variables
  SERVERFULL_RUNTIME_LOGGER_OUTPUT: "STDOUT"
  SERVERFULL_RUNTIME_LOGGER_LEVEL: "INFO"
  SERVERFULL_RUNTIME_STATS_OUTPUT: "NULL"
  SERVERFULL_RUNTIME_STATS_DATADOG_TAGS: ""
  SERVERFULL_RUNTIME_STATS_DATADOG_PACKETSIZE: 32768
  SERVERFULL_RUNTIME_STATS_DATADOG_FLUSHINTERVAL: 10s
  SERVERFULL_RUNTIME_STATS_DATADOG_ADDRESS: statsd:8125
  SERVERFULL_RUNTIME_SIGNALS_INSTALLED: OS
  SERVERFULL_RUNTIME_SIGNALS_OS_SIGNALS: 15 2
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVERFULL_RUNTIME_HTTPSERVER_ADDRESS: :8081
      SERVERFULL_RUNTIME_CONNSTATE_REPORTINTERVAL: 5s
      SERVERFULL_RUNTIME_CONNSTATE_HIJACKEDCOUNTER: http.server.connstate.hijacked
      SERVERFULL_RUNTIME_CONNSTATE_CLOSEDCOUNTER: http.server.connstate.closed
      SERVERFULL_RUNTIME_CONNSTATE_IDLEGAUGE: http.server.connstate.idle.gauge
      SERVERFULL_RUNTIME_CONNSTATE_IDLECOUNTER: http.server.connstate.idle
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVEGAUGE: http.server.connstate.active.gauge
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVECOUNTER: http.server.connstate.active
      SERVERFULL_RUNTIME_CONNSTATE_NEWGAUGE: http.server.connstate.new.gauge
      SERVERFULL_RUNTIME_CONNSTATE_NEWCOUNTER: http.server.connstate.new
      IPAMFACADE_LAMBDAMODE: "false"
      IPAMFACADE_PRODUCER_TYPE: "POST"
      IPAMFACADE_PRODUCER_BENTHOS_YAML: ""
      IPAMFACADE_PRODUCER_POST_ENDPOINT: "http://benthos-output:8086/publish"
      IPAMFACADE_PRODUCER_POST_HTTPCLIENT_TYPE: "DEFAULT"
      IPAMFACADE_PRODUCER_POST_HTTPCLIENT_DEFAULTCONFIG_CONTENTTYPE: "application/json"
      IPAMFACADE_PRODUCER_POST_HTTPCLIENT_SMART_OPENAPI: ""
      IPAMFACADE_DEVICE42CLIENT_ENDPOINT: "https://ipam-stg.net.atlassian.com"
      IPAMFACADE_DEVICE42CLIENT_LIMIT: 500
  gateway-incoming:
    build:
      context: .
      dockerfile: gateway-incoming.Dockerfile
    environment:
      <<: *common-variables
      PORTS_GATEWAY_INCOMING: "8080"
    ports:
      - "8080:8080"
  gateway-outgoing:
    build:
      context: .
      dockerfile: gateway-outgoing.Dockerfile
    environment:
      <<: *common-variables
      PORTS_GATEWAY_OUTGOING: "8082"
      IPAM_API_HOST: "https://ipam-stg.net.atlassian.com"
      IPAM_USERNAME: ""
      IPAM_PASSWORD: ""
      IPAM_TIMEOUT: "30s"
    ports:
      - "8082:8082"
