// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asecurityteam/ipam-facade/pkg/domain (interfaces: RandomNumberGenerator)

// Package v1 is a generated GoMock package.
package v1

import (
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	reflect "reflect"
)

// MockRandomNumberGenerator is a mock of RandomNumberGenerator interface
type MockRandomNumberGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRandomNumberGeneratorMockRecorder
}

// MockRandomNumberGeneratorMockRecorder is the mock recorder for MockRandomNumberGenerator
type MockRandomNumberGeneratorMockRecorder struct {
	mock *MockRandomNumberGenerator
}

// NewMockRandomNumberGenerator creates a new mock instance
func NewMockRandomNumberGenerator(ctrl *gomock.Controller) *MockRandomNumberGenerator {
	mock := &MockRandomNumberGenerator{ctrl: ctrl}
	mock.recorder = &MockRandomNumberGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRandomNumberGenerator) EXPECT() *MockRandomNumberGeneratorMockRecorder {
	return m.recorder
}

// NewRandom mocks base method
func (m *MockRandomNumberGenerator) NewRandom() (uuid.UUID, error) {
	ret := m.ctrl.Call(m, "NewRandom")
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRandom indicates an expected call of NewRandom
func (mr *MockRandomNumberGeneratorMockRecorder) NewRandom() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRandom", reflect.TypeOf((*MockRandomNumberGenerator)(nil).NewRandom))
}
