// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asecurityteam/ipam-facade/pkg/domain (interfaces: IPAMDataStorer)

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	domain "github.com/asecurityteam/ipam-facade/pkg/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIPAMDataStorer is a mock of IPAMDataStorer interface
type MockIPAMDataStorer struct {
	ctrl     *gomock.Controller
	recorder *MockIPAMDataStorerMockRecorder
}

// MockIPAMDataStorerMockRecorder is the mock recorder for MockIPAMDataStorer
type MockIPAMDataStorerMockRecorder struct {
	mock *MockIPAMDataStorer
}

// NewMockIPAMDataStorer creates a new mock instance
func NewMockIPAMDataStorer(ctrl *gomock.Controller) *MockIPAMDataStorer {
	mock := &MockIPAMDataStorer{ctrl: ctrl}
	mock.recorder = &MockIPAMDataStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPAMDataStorer) EXPECT() *MockIPAMDataStorerMockRecorder {
	return m.recorder
}

// StoreIPAMData mocks base method
func (m *MockIPAMDataStorer) StoreIPAMData(arg0 context.Context, arg1 domain.IPAMData) error {
	ret := m.ctrl.Call(m, "StoreIPAMData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreIPAMData indicates an expected call of StoreIPAMData
func (mr *MockIPAMDataStorerMockRecorder) StoreIPAMData(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreIPAMData", reflect.TypeOf((*MockIPAMDataStorer)(nil).StoreIPAMData), arg0, arg1)
}
