// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/asecurityteam/ipam-facade/pkg/domain (interfaces: PhysicalAssetStorer)

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	domain "github.com/asecurityteam/ipam-facade/pkg/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPhysicalAssetStorer is a mock of PhysicalAssetStorer interface
type MockPhysicalAssetStorer struct {
	ctrl     *gomock.Controller
	recorder *MockPhysicalAssetStorerMockRecorder
}

// MockPhysicalAssetStorerMockRecorder is the mock recorder for MockPhysicalAssetStorer
type MockPhysicalAssetStorerMockRecorder struct {
	mock *MockPhysicalAssetStorer
}

// NewMockPhysicalAssetStorer creates a new mock instance
func NewMockPhysicalAssetStorer(ctrl *gomock.Controller) *MockPhysicalAssetStorer {
	mock := &MockPhysicalAssetStorer{ctrl: ctrl}
	mock.recorder = &MockPhysicalAssetStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPhysicalAssetStorer) EXPECT() *MockPhysicalAssetStorerMockRecorder {
	return m.recorder
}

// StorePhysicalAssets mocks base method
func (m *MockPhysicalAssetStorer) StorePhysicalAssets(arg0 context.Context, arg1 domain.IPAMData) error {
	ret := m.ctrl.Call(m, "StorePhysicalAssets", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorePhysicalAssets indicates an expected call of StorePhysicalAssets
func (mr *MockPhysicalAssetStorerMockRecorder) StorePhysicalAssets(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorePhysicalAssets", reflect.TypeOf((*MockPhysicalAssetStorer)(nil).StorePhysicalAssets), arg0, arg1)
}
